import test from 'node:test';
import assert from 'node:assert/strict';
import {parseSequenceDataset,detectSequenceProfile,normalizedSequenceCSV} from '../sequence-data.mjs';
import {newCampaign,activeRound,applyPublishedCampaign} from '../data.mjs';
import {validateBackup} from '../io.mjs';

const nucb=`mutations,num_mutations,sublibrary_names,generations,activity_level,is_functional,sequence\n"()",0,"('g1_eppcr', 'g4_wt_synonyms')","('g1', 'g4')",activity > 0,True,ACDEFGHIK\n"(('A', 1, 'V'), ('C', 2, 'S'))",2,"('g2_ml',)","('g2',)",non-functional,False,VSDEFGHIK\n`;
const pcired=`variant,aa_seq,hamming_to_wildtype,fitness_20h,sigma_20h,fitness_percentile_20h,count_r1_in_20h,count_r1_out_20h,fitness_r1_uncorr_20h,sigma_r1_uncorr_20h,fitness_40h,sigma_40h,fitness_percentile_40h,count_r1_in_40h,count_r1_out_40h,fitness_r1_uncorr_40h,sigma_r1_uncorr_40h,positive_all_replicates_both_timepoints,positive_at_least_2_replicates_agreeing,fitness_avg\n,ACDEFGHIK,0,-0.05,0.4,0.8,100,80,-0.2,0.5,0.1,0.3,0.9,100,120,0.2,0.4,FALSE,FALSE,0.02\nA1V,VCDEFGHIK,1,#NAME?,#NAME?,,20,0,#NAME?,#NAME?,1.2,0.2,0.95,20,50,1.2,0.2,FALSE,TRUE,1.2\n`;

test('detects and normalizes the NucB landscape without inventing continuous activity',()=>{const d=parseSequenceDataset(nucb,'landscape.csv');assert.equal(d.profile,'nucb');assert.equal(d.summary.variants,2);assert.equal(d.summary.functional,1);assert.deepEqual(d.variants[0].generations,['g1','g4']);assert.deepEqual(d.variants[1].mutations,['A1V','C2S']);assert.equal(d.variants[1].metrics.activity_class,'non-functional');assert.equal(d.variants[1].metrics.fitness_avg,undefined);});
test('accepts the unnamed index column in the released NucB CSV',()=>{const indexed=nucb.replace(/^mutations,/,',mutations,').replace('\n"()",','\n0,"()",').replace('\n"((\'A\'', '\n1,"((\'A\'');const d=parseSequenceDataset(indexed);assert.equal(d.profile,'nucb');assert.equal(d.summary.variants,2);});
test('preserves PcIRED conditions, uncertainty, counts and missing spreadsheet errors',()=>{const d=parseSequenceDataset(pcired,'pcired-tecalcet-active_data.csv');assert.equal(d.profile,'pcired');assert.equal(d.variants[0].label,'WT');assert.equal(d.variants[1].metrics.fitness_20h,null);assert.equal(d.variants[1].metrics.fitness_40h,1.2);assert.equal(d.variants[1].counts[0].input,20);assert.equal(d.variants[1].counts[0].output,0);assert.equal(d.variants[1].agreement.atLeast2,true);assert.doesNotMatch(normalizedSequenceCSV(d),/fold/i);});
test('published templates carry structured goals and survive backup validation with source provenance',()=>{const c=applyPublishedCampaign(newCampaign(),'nucb'),r=activeRound(c),d=parseSequenceDataset(nucb);d.sourceFile={name:'landscape.csv',text:nucb,bytes:nucb.length,sha256:'test',importedAt:'2026-09-09'};r.sequenceDatasets.push(d);const restored=validateBackup(c);assert.equal(restored.origin,'published');assert.equal(restored.rounds[0].goal.referenceCondition,'Wild-type NucB at pH 9');assert.equal(restored.rounds[0].assay.screeningSystem,'droplet_sorting');assert.equal(restored.rounds[0].sequenceDatasets[0].summary.variants,2);});
test('rejects unknown layouts, invalid sequences and duplicate sequence identities',()=>{assert.throws(()=>detectSequenceProfile(['sequence','fitness']),/not a recognized/);assert.throws(()=>parseSequenceDataset(nucb.replace('ACDEFGHIK','ACDEXGHIK')),/unsupported symbols/);assert.throws(()=>parseSequenceDataset(nucb.replace('VSDEFGHIK','ACDEFGHIK')),/Duplicate amino-acid sequence/);});
