import{readFile,writeFile,mkdir,copyFile,readdir,access}from'node:fs/promises';
import{resolve,dirname,join,posix}from'node:path';
import{fileURLToPath}from'node:url';
import{execFileSync}from'node:child_process';
import{marked}from'marked';
const app=resolve(dirname(fileURLToPath(import.meta.url)),'..'),workspace=resolve(app,'../../..');
const exists=async p=>access(p).then(()=>true,()=>false);
const chapters=[['overview','Directed_Evolution_Handbook.md','Handbook overview'],['campaign','handbook/01_Campaign_and_Assays.md','Campaign and assays'],['libraries','handbook/02_Libraries_and_Expression.md','Libraries and expression'],['equipment','handbook/03_Equipment_and_Software.md','Equipment and software'],['examples','handbook/04_Worked_Examples.md','Three worked examples'],['progression','handbook/05_Progression_and_Troubleshooting.md','Progression and troubleshooting'],['advanced','handbook/06_Advanced_Methods.md','Advanced methods'],['using-app','handbook/07_Using_Evozyme.md','Using the app'],['pilot','handbook/Pilot_Kit.md','User pilot kit'],['toolkit','toolkit/README.md','Toolkit and formats'],['screen-example','toolkit/example/results/report.md','Synthetic screening report'],['sources','handbook/Sources.md','Sources'],['verification','handbook/Verification.md','Reference verification'],['starter','Directed_Evolution_Starter_Guide.md','Compact starter guide']];
const assets=[['handbook/Pilot_Kit.md','downloads/Pilot_Kit.md'],['handbook/07_Using_Evozyme.md','downloads/Using_Evozyme.md'],['outputs/presentation/Evozyme_Directed_Evolution_v2.pptx','downloads/Evozyme_Directed_Evolution_v2.pptx'],['outputs/01a084fa-2400-76c2-b42b-dfc42ca3fbad/Evozyme_Planners.xlsx','downloads/Evozyme_Planners.xlsx'],['toolkit/evozyme.py','downloads/evozyme.py'],['toolkit/requirements.txt','downloads/requirements.txt'],...['Campaign_Brief.md','Round_Review.md','Equipment_Acceptance.md','plate_map.csv','clone_register.csv','measurements.csv','assay_record.csv','probabilities.csv'].map(n=>['toolkit/templates/'+n,'downloads/'+n]),...['assay.json','plate_map.csv','clone_register.csv','measurements.csv','confirmation.csv','nnk_probabilities.csv','measurements_wide_minutes.csv'].map(n=>['toolkit/example/'+n,'example/'+n]),...['candidates.csv','quality.json','well_results.csv','quality_plots.png'].map(n=>['toolkit/example/results/'+n,'example/results/'+n])];
await mkdir(join(app,'guide'),{recursive:true});await mkdir(join(app,'content'),{recursive:true});
for(const[,source]of chapters){const dest=join(app,'content',source);await mkdir(dirname(dest),{recursive:true});if(await exists(join(workspace,source)))await copyFile(join(workspace,source),dest);if(!await exists(dest))throw new Error('Missing guide source: '+source);}
for(const[source,target]of assets){const dest=join(app,target);await mkdir(dirname(dest),{recursive:true});if(await exists(join(workspace,source)))await copyFile(join(workspace,source),dest);if(!await exists(dest))throw new Error('Missing asset: '+target);}
const targets=new Map(chapters.map(([id,source])=>[source,'#'+id]));for(const[source,target]of assets)targets.set(source,'../'+target);
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let sections='';for(const[id,source,title]of chapters){let md=await readFile(join(app,'content',source),'utf8');
  // Correct a wording ambiguity during publication: both screens retain C03 > C11.
  md=md.replace('to show a changed ranking:','to show that a screening gain may not persist in confirmation:');
  let html=marked.parse(md,{gfm:true});html=html.replace(/(href|src)="([^"]+)"/g,(whole,attr,href)=>{if(/^(https?:|mailto:|#)/.test(href))return whole;const pathname=href.split('#')[0],normalized=posix.normalize(posix.join(posix.dirname(source),pathname));const dest=targets.get(normalized);if(dest)return`${attr}="${dest}"`;return whole;});
  html=html.replace(/<table>/g,'<div class="table-wrap"><table>').replace(/<\/table>/g,'</table></div>').replace(/<h1>/g,'<h2>').replace(/<\/h1>/g,'</h2>');sections+=`<section class="guide-section" id="${id}" data-search-title="${escape(title)}">${html}</section>\n`;}
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Evozyme Handbook</title><meta name="description" content="A practical guide to cost-efficient directed evolution of enzymes, equipment, assays, libraries, and data review."><link rel="stylesheet" href="../style.css"><link rel="stylesheet" href="../overview.css"><style>@media print{.site-header,.guide-controls,footer{display:none}.sheet{border:0;padding:0;margin:0}.guide-body{max-width:none}}</style><script defer src="guide.js"></script></head><body><div class="sheet"><header class="site-header"><a class="site-title" href="/">Magnus Lian Akerholt</a><nav aria-label="Main navigation"><a href="/">Home</a><a href="/apps/">Apps</a><a href="/articles/">Articles</a><a href="/art/">Art</a></nav></header><main class="guide-body"><h1>Evozyme handbook</h1><p><a href="../planner.html">← Return to the planner</a> · Edition 2 · App workflow 1.2 · 9 September 2026</p><div class="guide-controls"><div class="overview-entry"><p><strong>Start with the process map.</strong><br>See how planning, laboratory work and each round connect.</p><a class="button-like" href="../">View the overview →</a></div><label class="field"><span>Search handbook chapters</span><input id="guide-search" type="search" placeholder="e.g. plate reader, confirmation, NNK"></label><p id="search-count" role="status"></p><nav class="guide-index" aria-label="Handbook chapters">${chapters.map(([id,,title])=>`<a href="#${id}">${escape(title)}</a>`).join('')}</nav><div class="callout"><strong>Downloads</strong><p><a href="../downloads/Evozyme_Directed_Evolution_v2.pptx" download>PowerPoint presentation</a> · <a href="../downloads/Evozyme_Planners.xlsx" download>Planning workbook</a> · <a href="../downloads/evozyme.py" download>Python analysis toolkit</a></p><p>Routine equipment and standard protocols are listed briefly. Detailed guidance focuses on the decisions needed to make the workflow work.</p></div></div>${sections}</main></div><footer><a href="../">Back to Evozyme</a> · <a href="/apps/">Back to apps</a></footer></body></html>`;
await writeFile(join(app,'guide/index.html'),html);
await writeFile(join(app,'guide/guide.js'),`const search=document.querySelector('#guide-search'),sections=[...document.querySelectorAll('.guide-section')];search.addEventListener('input',()=>{const q=search.value.toLowerCase().trim();let n=0;for(const s of sections){s.hidden=q&&!s.textContent.toLowerCase().includes(q);if(!s.hidden)n++;}document.querySelector('#search-count').textContent=q?n+' chapters match.':'';});window.addEventListener('hashchange',()=>{search.value='';sections.forEach(s=>s.hidden=false);document.querySelector('#search-count').textContent='';document.getElementById(location.hash.slice(1))?.scrollIntoView();});`);
for(const file of await readdir(app))if(file.endsWith('.mjs'))execFileSync(process.execPath,['--check',join(app,file)]);
const overview=await readFile(join(app,'overview.html'),'utf8');
await writeFile(join(app,'index.html'),overview.replace('</head>','  <script src="entry.js"></script>\n</head>'));
const pages=[['guide/index.html',html],['overview.html',await readFile(join(app,'overview.html'),'utf8')],['index.html',await readFile(join(app,'index.html'),'utf8')],['planner.html',await readFile(join(app,'planner.html'),'utf8')]];
for(const[page,markup]of pages){const links=[...markup.matchAll(/(?:href|src)="([^"]+)"/g)].map(m=>m[1]);for(const link of links){if(/^(https?:|mailto:|#|\/)/.test(link))continue;const path=join(app,dirname(page),link.split('#')[0]);if(!await exists(path))throw new Error('Broken local link in '+page+': '+link);}}
console.log('Built 14 handbook sections, checked browser modules and local app, overview and guide links.');
