import {header} from '../desk.mjs';
import{readFile,writeFile,mkdir,copyFile,readdir,access}from'node:fs/promises';
import{resolve,dirname,join,posix}from'node:path';
import{fileURLToPath}from'node:url';
import{execFileSync}from'node:child_process';
import{marked}from'marked';
const app=resolve(dirname(fileURLToPath(import.meta.url)),'..'),workspace=resolve(app,'../../..');
const exists=async p=>access(p).then(()=>true,()=>false);
const chapters=[['overview','Directed_Evolution_Handbook.md','Handbook overview'],['campaign','handbook/01_Campaign_and_Assays.md','Campaign and assays'],['libraries','handbook/02_Libraries_and_Expression.md','Libraries and expression'],['equipment','handbook/03_Equipment_and_Software.md','Equipment and software'],['examples','handbook/04_Worked_Examples.md','Three worked examples'],['progression','handbook/05_Progression_and_Troubleshooting.md','Progression and troubleshooting'],['advanced','handbook/06_Advanced_Methods.md','Advanced methods'],['using-app','handbook/07_Using_Evozyme.md','Using the app'],['pilot','handbook/Pilot_Kit.md','User pilot kit'],['toolkit','toolkit/README.md','Toolkit and formats'],['screen-example','toolkit/example/results/report.md','Synthetic screening report'],['sources','handbook/Sources.md','Sources'],['verification','handbook/Verification.md','Reference verification'],['starter','Directed_Evolution_Starter_Guide.md','Compact starter guide']];
const assets=[['handbook/Pilot_Kit.md','downloads/Pilot_Kit.md'],['handbook/07_Using_Evozyme.md','downloads/Using_Evozyme.md'],['outputs/presentation/Evozyme_Directed_Evolution_v2.pptx','downloads/Evozyme_Directed_Evolution_v2.pptx'],['outputs/01a084fa-2400-76c2-b42b-dfc42ca3fbad/Evozyme_Planners.xlsx','downloads/Evozyme_Planners.xlsx'],['toolkit/evozyme.py','downloads/evozyme.py'],['toolkit/requirements.txt','downloads/requirements.txt'],...['Campaign_Brief.md','Round_Review.md','Equipment_Acceptance.md','plate_map.csv','clone_register.csv','measurements.csv','assay_record.csv','probabilities.csv'].map(n=>['toolkit/templates/'+n,'downloads/'+n]),...['assay.json','plate_map.csv','clone_register.csv','measurements.csv','confirmation.csv','nnk_probabilities.csv','measurements_wide_minutes.csv'].map(n=>['toolkit/example/'+n,'example/'+n]),...['candidates.csv','quality.json','well_results.csv','quality_plots.png'].map(n=>['toolkit/example/results/'+n,'example/results/'+n])];
await mkdir(join(app,'guide'),{recursive:true});await mkdir(join(app,'content'),{recursive:true});
for(const[,source]of chapters){const dest=join(app,'content',source);await mkdir(dirname(dest),{recursive:true});if(await exists(join(workspace,source)))await copyFile(join(workspace,source),dest);if(!await exists(dest))throw new Error('Missing guide source: '+source);}
for(const[source,target]of assets){const dest=join(app,target);await mkdir(dirname(dest),{recursive:true});if(await exists(join(workspace,source)))await copyFile(join(workspace,source),dest);if(!await exists(dest))throw new Error('Missing asset: '+target);}
const targets=new Map(chapters.map(([id,source])=>[source,'#'+id]));for(const[source,target]of assets)targets.set(source,'../'+target);
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let sections='';for(const[id,source,title]of chapters){let md=await readFile(join(app,'content',source),'utf8');
  // Correct a wording ambiguity during publication: both screens retain C03 > C11.
  md=md.replace('to show a changed ranking:','to show that a screening gain may not persist in confirmation:');
  let html=marked.parse(md,{gfm:true});html=html.replace(/(href|src)="([^"]+)"/g,(whole,attr,href)=>{if(/^(https?:|mailto:|#)/.test(href))return whole;const pathname=href.split('#')[0],normalized=posix.normalize(posix.join(posix.dirname(source),pathname));const dest=targets.get(normalized);if(dest)return`${attr}="${dest}"`;return whole;});
  html=html.replace(/<table>/g,'<div class="table-wrap"><table>').replace(/<\/table>/g,'</table></div>').replace(/<h1>/g,'<h2>').replace(/<\/h1>/g,'</h2>');sections+=`<section class="guide-section" id="${id}" data-search-title="${escape(title)}">${html}</section>\n`;}
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>Evozyme Guide</title><meta name="description" content="A practical guide to directed evolution of enzymes."><link rel="stylesheet" href="../style.css"><script type="module" src="../handbook.mjs"></script></head><body class="handbook"><a class="skip" href="#reading">Skip to chapter</a><div class="sheet">${header('../','Guide')}<main><div class="reading-heading"><p class="eyebrow">Guide</p><h1>Directed evolution reference</h1><span id="context-loading" class="selection-note">Loading campaign context…</span><a id="context-return" hidden href="../planner.html">← Open your campaign</a><noscript><style>#context-loading{display:none}</style><a href="../planner.html">Open your campaign →</a></noscript></div><div class="reading-layout"><nav class="guide-controls" aria-label="Guide chapters"><label class="field"><span>Find a chapter</span><input id="guide-search" type="search" placeholder="e.g. confirmation"></label><p id="search-count" role="status"></p><div class="guide-index">${chapters.map(([id,,title],i)=>`<a href="#${id}"><span>${String(i+1).padStart(2,'0')}</span>${escape(title)}</a>`).join('')}</div><p><a href="../files.html">Templates &amp; downloads →</a></p></nav><article id="reading" class="guide-body">${sections}<nav id="chapter-paging" aria-label="Previous and next chapter"></nav></article></div></main></div><footer><a href="../">Evozyme overview</a> · <a href="/apps/">All apps</a> · App 1.5</footer></body></html>`;
await writeFile(join(app,'guide/index.html'),html);
for(const file of await readdir(app))if(file.endsWith('.mjs'))execFileSync(process.execPath,['--check',join(app,file)]);
const overview=await readFile(join(app,'overview.html'),'utf8');
await writeFile(join(app,'index.html'),overview.replace('</head>','  <script src="entry.js"></script>\n</head>'));
const pages=[['guide/index.html',html],['overview.html',await readFile(join(app,'overview.html'),'utf8')],['index.html',await readFile(join(app,'index.html'),'utf8')],['planner.html',await readFile(join(app,'planner.html'),'utf8')],['files.html',await readFile(join(app,'files.html'),'utf8')]];
for(const[page,markup]of pages){const links=[...markup.matchAll(/(?:href|src)="([^"]+)"/g)].map(m=>m[1]);for(const link of links){if(/^(https?:|mailto:|#|\/)/.test(link))continue;const path=join(app,dirname(page),link.split(/[?#]/)[0]);if(!await exists(path))throw new Error('Broken local link in '+page+': '+link);}}
console.log('Built 14 handbook sections, checked browser modules and local app, overview and guide links.');
