import{SCHEMA_VERSION}from'./io.mjs';
export const CONTENT_VERSION='2026-09-09';
export const uid=()=>crypto.randomUUID();
export const stages=['Campaign','Assay','Equipment','Library','Budget','Screen','Review'];
export const screeningSystems={
 plate_absorbance:{name:'96-well kinetic absorbance',status:'Built-in analysis',description:'Track an absorbance signal over a validated linear interval for individually identified preparations.',bestFor:'Colorimetric products, cofactors such as NAD(P)H, or justified coupled assays.',watch:'Confirm path length or calibration before reporting concentration rates; check matrix absorbance and detector limits.',sourceName:'Assay Guidance Manual — enzyme assays',source:'https://www.ncbi.nlm.nih.gov/books/NBK92007/',assay:{detection:'Absorbance',sampleFormat:'Clarified cell lysate',signal_unit:'AU',normalization:'Signal units/minute; no protein normalization',fit_times:'0, 30, 60, 90, 120, 150, 180'},budget:{wells:96,technical:2,preparations:1}},
 plate_fluorescence:{name:'96-well kinetic fluorescence',status:'Built-in analysis',description:'Track a fluorogenic product or coupled reporter over a validated linear interval in identified wells.',bestFor:'Sensitive plate assays with a specific fluorogenic substrate or reporter.',watch:'Test quenching, spectral interference, product leakage and matrix-specific calibration.',sourceName:'Chitinase FACS study — plate assays and fluorogenic linkage',source:'https://pmc.ncbi.nlm.nih.gov/articles/PMC8002391/',assay:{detection:'Fluorescence',sampleFormat:'Clarified cell lysate',signal_unit:'RFU',normalization:'Signal units/minute; no protein normalization',fit_times:'0, 30, 60, 90, 120, 150, 180'},budget:{wells:96,technical:2,preparations:1}},
 plate_luminescence:{name:'96-well kinetic luminescence',status:'Built-in analysis',description:'Track a luminescent reporter over time when the reporter chemistry is demonstrably proportional to the intended reaction.',bestFor:'Sensitive coupled assays with compatible kinetics and plate-reader access.',watch:'Show that reporter capacity, timing and reagent stability do not limit or distort variant ranking.',sourceName:'Assay Guidance Manual — enzyme assays',source:'https://www.ncbi.nlm.nih.gov/books/NBK92007/',assay:{detection:'Luminescence',sampleFormat:'Clarified cell lysate',signal_unit:'RLU',normalization:'Signal units/minute; no protein normalization',fit_times:'0, 30, 60, 90, 120, 150, 180'},budget:{wells:96,technical:2,preparations:1}},
 plate_endpoint:{name:'Microplate endpoint assay',status:'Planning only',description:'Measure one defined endpoint per well after a controlled reaction interval.',bestFor:'Stable endpoint chemistry when kinetic acquisition is impractical.',watch:'Endpoint timing and reaction completion can hide rate differences. The Evozyme analyser currently requires time-course data.',sourceName:'Assay Guidance Manual — enzyme assays',source:'https://www.ncbi.nlm.nih.gov/books/NBK92007/',assay:{detection:'Other — planning only',sampleFormat:'Clarified cell lysate',signal_unit:'AU',normalization:'Endpoint signal; assay-specific normalization'},budget:{wells:96,technical:2,preparations:1}},
 colony_imaging:{name:'Colony or agar imaging',status:'Planning only',description:'Rank spatially separated colonies or spots using a localized color, fluorescence or halo signal.',bestFor:'Reactions whose signal remains localized and whose source clone can be recovered.',watch:'Growth, diffusion, illumination and position can drive the score; confirm hits in an independent biochemical assay.',sourceName:'Directed evolution of bacterial α-amylase',source:'https://pmc.ncbi.nlm.nih.gov/articles/PMC2366932/',assay:{detection:'Other — planning only',sampleFormat:'Agar colony or arrayed spot',signal_unit:'Image-derived score',normalization:'Image score with colony-size and position review'}},
 cell_sorting:{name:'Cellular reporter with FACS',status:'Planning only',description:'Sort individual cells when enzymatic activity can be linked to a retained fluorescent cellular signal.',bestFor:'Very large libraries with a validated intracellular, surface-display or compartment-linked reporter.',watch:'Expression, transport and reporter behavior can outrank catalysis; demonstrate recovery and biochemical confirmation.',sourceName:'FACS screening of chitinase A',source:'https://pmc.ncbi.nlm.nih.gov/articles/PMC8002391/',assay:{detection:'Other — planning only',sampleFormat:'Single-cell suspension',signal_unit:'Cell fluorescence',normalization:'Reporter signal per cell; assay-specific'}},
 droplet_sorting:{name:'Droplet microfluidic sorting',status:'Planning only',description:'Compartmentalize genotype and enzyme reaction, then detect and sort droplets.',bestFor:'Ultra-high-throughput assays with a stable compartment-compatible reporter and reliable genotype recovery.',watch:'Validate loading, leakage, occupancy, sorting error and post-sort recovery before scaling.',sourceName:'Agresti et al. droplet enzyme evolution',source:'https://pmc.ncbi.nlm.nih.gov/articles/PMC2840095/',assay:{detection:'Other — planning only',sampleFormat:'Single-variant droplet compartment',signal_unit:'Droplet fluorescence',normalization:'Droplet reporter signal; assay-specific'}},
 growth_selection:{name:'Growth-coupled selection',status:'Planning only',description:'Link the desired enzyme activity to host survival or growth under a defined selective condition.',bestFor:'Reactions with a credible, tunable connection between target chemistry and cellular fitness.',watch:'Growth may reflect expression, bypasses or host adaptation rather than catalytic improvement; reconstruct and retest variants.',sourceName:'Growth selection for amine-forming enzymes',source:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9718777/',assay:{detection:'Other — planning only',sampleFormat:'Selective culture',signal_unit:'Growth or enrichment',normalization:'Growth/enrichment under defined selection pressure'}}
};
export const parameterSuggestions={
 metric:['Initial intended-product rate','Initial surrogate-signal rate','Residual activity after defined exposure','Desired-product fraction','Useful activity per culture volume','Activity per target-enzyme amount'],
 units:['AU/min','RFU/min','RLU/min','µM/min','U/mL culture','min⁻¹','% residual activity','% desired product','fold vs parent'],
 host:['Escherichia coli','Bacillus subtilis','Komagataella phaffii (Pichia pastoris)','Saccharomyces cerevisiae','Cell-free expression','Other / assay-specific'],
 sampleFormat:['Clarified cell lysate','Whole-cell suspension','Purified enzyme','Cell-free expression reaction','Agar colony or arrayed spot','Single-cell suspension','Single-variant droplet compartment'],
 normalization:['Signal units/minute; no protein normalization','Product rate per culture volume','Product rate per total protein','Product rate per target-enzyme amount','Whole-cell signal per cell','Reporter ratio','Assay-specific normalization'],
 confirmation:['HPLC or LC–MS product analysis','GC or GC–MS product analysis','Orthogonal intended-substrate assay','Purified-enzyme kinetic characterization','Product identity plus activity measurement']
};
export function applyScreeningSystem(r,id){const preset=screeningSystems[id];if(!preset)throw new Error('Choose a supported screening-system starting point.');r.assay.screeningSystem=id;Object.assign(r.assay,preset.assay,{rulesReviewed:false,reviewRecord:null});if(preset.budget)Object.assign(r.budget,preset.budget);return preset;}
export const configurations={shared:{name:'Shared laboratory pilot',description:'Use shared construction and reader access, manual multichannel handling, and outsourced sequencing to establish feasibility.'},manual:{name:'Dedicated manual screening',description:'Book or dedicate plate-compatible culture, preparation, and reader capacity for repeated campaigns. Keep reliable manual exception handling.'},automated:{name:'Partly automated screening',description:'Add a liquid handler and traceable transfer records after a measured repetitive bottleneck justifies integration, maintenance, and verification.'}};
const equipment=[
 ['reader','Activity plate reader','Demonstrate the actual detection mode/wavelength, signal range, read timing, temperature, mixing, and raw well/time export.'],
 ['handling','Plate-scale liquid handling','Multichannel pipette, tips and reservoirs; check transfer accuracy at the intended volumes and sample properties.'],
 ['culture','Plate culture and shaking','Compatible culture plates, seals, holders, working volumes, temperature, and sufficient booked capacity.'],
 ['centrifuge','Plate centrifugation','Verify plate height, carriers, rotor and intended cell-pelleting operation. A plate spinner may be insufficient.'],
 ['preparation','Sample preparation and recovery','Reproducible lysis/recovery and a retained, recoverable source stock for every clone.'],
 ['construction','DNA construction and checks','Thermocycler, gel/imaging and cloning access; electroporation only if the selected workflow requires it.'],
 ['sequencing','Sequence verification','Accessible sequencing service, turnaround time, sequence files, and traceable numbering.'],
 ['confirmation','Intended-product confirmation','Appropriate product analysis and protein preparation/quantification access; reserve capacity for independent preparations.'],
 ['stocks','Stock storage and tracking','Stable clone IDs, storage locations, recovery checks, cold storage, and backup records.'],
 ['routine','Routine laboratory infrastructure','Pipettes, microcentrifuge, vortex, incubators, heating, balance, pH, water/sterilization, refrigeration/freezers, and consumables.'],
 ['computer','Computer and acquisition support','Working instrument drivers, license, cables, supported operating system, and readable raw-data exports.']
];
export function defaultEquipment(){return equipment.map(([id,name,requirement])=>({id,name,requirement,access:'missing',quantity:1,price:null,instrument:'',specification:'',accessories:'',compatibility:'',evidence:'',constraints:'',quoteDate:'',source:'',exclusions:''}));}
export const softwareList=[
 ['sequence','Sequence editing','ApE or an existing sequence editor','https://jorgensen.biology.utah.edu/wayned/ape/'],
 ['primers','Method-compatible primer design','NEBaseChanger for the supported Q5 workflow, or the tool matching your method','https://nebasechanger.neb.com/'],
 ['acquisition','Instrument acquisition','Supported vendor software; retain raw observations and acquisition settings',''],
 ['tracking','Tracking and planning','Evozyme, plus spreadsheet software for exported records','https://www.libreoffice.org/'],
 ['analysis','Repeatable analysis','Evozyme for supported 96-well linear-rate screens; reference Python toolkit available','downloads/evozyme.py'],
 ['backup','Backup and restoration','Managed second copy of records, raw data, sequence files and stock register','']
];
export function defaultBudget(){return{primaryPlates:4,wells:96,controls:16,technical:2,preparations:1,usableFraction:.9,repeatPlates:1,confirmCandidates:8,confirmPreps:3,laborHours:24,laborRate:450,prepCost:20,wellCost:3,libraryCost:1500,sequenceCost:100,confirmationCost:75,readerRate:150,readerHours:3,contingency:.1,otherCost:0,controlPrepCost:0};}
export function newRound(number=1,parentRoundId=null){return{id:uid(),number,parentRoundId,createdAt:new Date().toISOString(),brief:{owner:'',parent:'',parentCloneId:'PARENT',sequenceReference:'',reaction:'',objective:'',metric:'',units:'',conditions:'',secondary:'',host:'',format:'',minimumImprovement:'',effort:'',stockPlan:'',backupLocation:'',startEvidence:'',stopRule:''},assay:{screeningSystem:'plate_absorbance',reference_parent_id:'PARENT',reviewRecord:null,run_id:'',assay_id:'',data_origin:'User-entered data',signal_unit:'AU',signal_direction:1,fit_times:'0, 30, 60, 90, 120, 150, 180',signal_ceiling:1,signal_floor:null,minimum_r2:.98,maximum_parent_cv:.15,maximum_technical_cv:.15,maximum_host_fraction:.1,minimum_blank_wells:4,minimum_host_wells:4,minimum_parent_preparations:4,minimum_technical_wells:2,minimum_fold_for_retest:1.2,detection:'Absorbance',sampleFormat:'Clarified cell lysate',normalization:'Signal units/minute; no protein normalization',productMethod:'',protocolReference:'',rangeChecked:false,backgroundChecked:false,timingChecked:false,repeatabilityChecked:false,recoveryChecked:false,rulesReviewed:false},configuration:'shared',equipment:defaultEquipment(),software:softwareList.map(([id,name,suggestion,url])=>({id,name,suggestion,url,ready:false,choice:'',version:'',retainedOutput:''})),library:{strategy:'Focused site saturation',model:'nnk',draws:96,targets:20,offTargetLoss:0,custom:'target,probability_per_draw\nA,0.5\nB,0.5\n',rationale:'',sequenceCheck:'',pilotCapacity:''},budget:defaultBudget(),budgetScenarios:[],files:{},analyses:[],confirmation:[],confirmationSource:null,evidence:[],costsReviewed:false,criteria:{enabled:false,assayId:'',normalization:'product',direction:'at_least',fold:null,notes:''},review:{referenceReason:'',parentCloneId:'PARENT',normalization:'product',action:'',rationale:'',chosenClone:'',changedConditions:'',comparisonPanel:'',actualClones:null,actualUnique:null,actualValid:null,actualHours:null,actualCost:null,archive:'',backupChecked:false,unresolved:'',reviewer:'',reviewedAt:''}};}
export function newCampaign(){const r=newRound();return{schemaVersion:SCHEMA_VERSION,revision:0,guided:true,mappingPresets:[],restorationCheckedAt:null,contentVersion:CONTENT_VERSION,id:uid(),name:'Untitled campaign',currency:'NOK',origin:'user',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lastExportAt:null,activeRoundId:r.id,rounds:[r]};}
export function assayConfig(assay){const keys=['reference_parent_id','run_id','assay_id','data_origin','signal_unit','signal_direction','signal_ceiling','signal_floor','minimum_r2','maximum_parent_cv','maximum_technical_cv','maximum_host_fraction','minimum_blank_wells','minimum_host_wells','minimum_parent_preparations','minimum_technical_wells','minimum_fold_for_retest'];return{...Object.fromEntries(keys.map(k=>[k,assay[k]])),fit_times_s:assay.fit_times.trim()?assay.fit_times.split(/[,;\s]+/).filter(Boolean).map(Number):[]};}
export function activeRound(c){return c.rounds.find(r=>r.id===c.activeRoundId);}
export function nextRound(c,clone){const old=activeRound(c),r=newRound(Math.max(...c.rounds.map(x=>x.number))+1,old.id);for(const k of ['brief','assay','equipment','software','library','budget'])r[k]=structuredClone(old[k]);r.configuration=old.configuration;r.brief.parent=clone===old.brief.parentCloneId?old.brief.parent:clone;r.brief.parentCloneId=clone;r.brief.sequenceReference=clone===old.brief.parentCloneId?old.brief.sequenceReference:old.evidence.find(e=>e.clone_id===clone)?.sequenceReference||'';r.assay.run_id='';r.assay.reference_parent_id=clone;r.assay.rulesReviewed=false;r.assay.reviewRecord=null;r.criteria=structuredClone(old.criteria);r.costsReviewed=old.costsReviewed;r.review.parentCloneId=clone;c.rounds.push(r);c.activeRoundId=r.id;return r;}
export const budgetFields=[['primaryPlates','Primary plates','plates',1],['wells','Wells per plate','wells',1],['controls','Controls per plate','wells',1],['technical','Technical wells per preparation','wells',1],['preparations','Preparations per clone','preparations',1],['usableFraction','Expected usable fraction','0–1',.01],['repeatPlates','Reserved repeat plates','plates',1],['confirmCandidates','Confirmation candidates','clones',1],['confirmPreps','Independent confirmations per candidate','preparations',1],['laborHours','Hands-on labor','hours',.5],['laborRate','Labor cost','per hour',1],['prepCost','Culture and preparation','per preparation',.1],['wellCost','Assay cost','per well',.1],['libraryCost','Library construction','per round',1],['sequenceCost','Sequencing','per candidate',1],['confirmationCost','Confirmation consumables','per preparation',1],['readerRate','Reader access','per hour',1],['readerHours','Reader booking','hours',.5],['controlPrepCost','Additional control preparation','per round',1],['otherCost','Other recurring costs','per round',1],['contingency','Contingency fraction','0–1 or higher',.01]];
export const strategies=[['Focused site saturation','Explore a small defined target set when positions are justified and capacity is limited.'],['Error-prone PCR','Broader random variation; verify mutation distribution and retain enough capacity for low-activity variants.'],['Recombination','Combine characterized variation while retaining lineage and sequence checks.'],['Custom library','Record the construction strategy, target probabilities, and sampling assumptions explicitly.']];
