import {field,heading,e,table,callout,num,date} from './ui.mjs';
import {confirmationSummary} from './core.mjs';
export const setupPaths=['name','brief.parent','brief.parentCloneId','brief.objective','brief.metric','brief.units','brief.conditions'];
export function setupView(c,r){return heading(1,'Start your campaign','Begin with the parent, intended improvement and a fair comparison. Details can be added as you work through the stages.')+`<fieldset><legend>Starting information</legend><div class="form-grid two">${field(c,'name','Campaign name',{placeholder:'e.g. LipA activity pilot'})}${field(r,'brief.parent','Parent enzyme',{placeholder:'e.g. LipA; add accession later'})}${field(r,'brief.parentCloneId','Parent clone ID',{hint:'An exact tracking label, e.g. PARENT. Used in screen and stock records.'})}${field(r,'brief.objective','What should improve?',{type:'textarea',hint:'e.g. Increase intended-product rate while preserving stability.'})}${field(r,'brief.metric','Improvement metric',{placeholder:'e.g. intended-product rate'})}${field(r,'brief.units','Metric units',{placeholder:'e.g. µM/min'})}${field(r,'brief.conditions','Comparison conditions',{type:'textarea',hint:'Record substrate, pH, temperature and normalization for a fair comparison.'})}${field(r,'assay.detection','Measurement route',{options:['Absorbance','Fluorescence','Luminescence','Other — planning only']})}</div><p>Starting information is saved as you type. Assay evidence and reviewed settings are needed before using a screen to make decisions.</p><a href="#assay" class="button-like">Continue to the assay →</a> · <a href="guide/index.html#campaign">Campaign and assay guidance</a></fieldset>`;}
export function criteriaResults(r){
  const k=r.criteria;if(!k?.enabled)return[];
  if(!k.assayId.trim()||!Number.isFinite(k.fold)||k.fold<=0)return[{clone:'—',status:'Needs a named assay and a positive target ratio.'}];
  if(k.normalization!==r.review.normalization)return[{clone:'—',status:'Normalization differs from the confirmation view. Select compatible units before comparing.'}];
  let rows;try{rows=confirmationSummary(r.confirmation,r.review.parentCloneId,k.normalization);}catch(err){return[{clone:'—',status:err.message}];}
  rows=rows.filter(x=>x.assay_id===k.assayId&&x.clone_id!==r.review.parentCloneId);
  if(!rows.length)return[{clone:'—',status:'No observations for this exact assay ID. Free-text goals still require interpretation.'}];
  return rows.map(x=>({clone:x.clone_id,fold:x.fold,status:x.fold===null?'Comparable reference unavailable':(k.direction==='at_least'?x.fold>=k.fold:x.fold<=k.fold)?'Observed mean ratio meets the recorded target':'Observed mean ratio does not meet the recorded target'}));
}
export function goalContext(r){return`<section class="panel"><h3>Goal and confirmation context</h3><p><strong>Intended improvement:</strong> ${e(r.brief.objective||'Not recorded')}</p><p>${e(r.brief.metric||'Metric not recorded')} · ${e(r.brief.units||'Units not recorded')}<br>${e(r.brief.conditions||'Comparison conditions not recorded')}</p><p><strong>Properties to preserve:</strong> ${e(r.brief.secondary||'Not recorded')}</p><p>Screen reference: ${e(r.assay.reference_parent_id)} · Confirmation reference: ${e(r.review.parentCloneId)}<br>Comparison change: ${e(r.review.referenceReason||'None recorded')}</p><details><summary>Optional structured confirmation target</summary><p>Compare a dimensionless fold ratio only within a named assay and matching normalization. This describes observed means; it does not decide whether to advance a clone or establish statistical significance.</p><label class="check"><input type="checkbox" data-field="criteria.enabled" ${r.criteria.enabled?'checked':''}><span>Use a structured target alongside the written goal</span></label><div class="form-grid two">${field(r,'criteria.assayId','Exact confirmation assay ID')}${field(r,'criteria.normalization','Target normalization',{options:[['product','Product rate (µM/min)'],['enzyme','Product rate / enzyme concentration (min⁻¹)']]})}${field(r,'criteria.direction','Target direction',{options:[['at_least','At least this ratio'],['at_most','At most this ratio']]})}${field(r,'criteria.fold','Target fold versus reference',{type:'number',min:0})}${field(r,'criteria.notes','Target meaning / remaining uncertainties',{type:'textarea',wide:true})}</div></details><div id="criteria-output">${criteriaTable(r)}</div></section>`;}
export function criteriaTable(r){return r.criteria.enabled?table(['Clone','Observed fold','Target comparison'],criteriaResults(r).map(x=>[e(x.clone),num(x.fold,3),e(x.status)])):'<p>The written goal is retained for analyst interpretation.</p>';}
export function archiveContext(c,r){return`<section class="panel"><h3>Backup and external evidence</h3><p>Last backup download: ${e(date(c.lastExportAt))}<br>Last separate-copy restore: ${e(date(c.restorationCheckedAt))}</p><p>External backup: ${e(r.brief.backupLocation||'Location not recorded')}<br>Archive: ${e(r.review.archive||'Location not recorded')}</p><p>Sequence files and product/property evidence are external references unless explicitly imported. Keep those files beside the JSON backup. After restoring a separate copy, open its raw inputs and confirmation records and check these external locations.</p><button data-action="restore-check">Check a backup by restoring a separate copy</button></section>`;}
