import {field,heading,e,table,callout,num,date} from './ui.mjs';
import {confirmationSummary} from './core.mjs';
import {screeningSystems,parameterSuggestions,publishedCampaignTemplates} from './data.mjs';
export const setupPaths=['name','brief.parent','brief.parentCloneId','brief.objective','brief.metric','brief.units','brief.conditions'];
export function setupIssues(c,r,step){const fields=step===1?[["name",c.name,"Give the campaign a name."],["brief.parent",r.brief.parent,"Name the parent enzyme."],["brief.parentCloneId",r.brief.parentCloneId,"Enter a parent clone ID for tracking."],["brief.objective",r.brief.objective,"Describe the improvement you want to measure."]]:step===3?[["brief.metric",r.brief.metric,"Name the improvement metric."],["brief.units",r.brief.units,"Enter the metric units."],["brief.conditions",r.brief.conditions,"Record the comparison conditions."]]:[];return fields.filter(([,v])=>!String(v||'').trim()).map(([path,,message])=>({path,message}));}
export function screeningSystemSummary(r){const s=screeningSystems[r.assay.screeningSystem]||screeningSystems.plate_absorbance;return`<div class="screening-summary"><p><span class="tag ${s.status==='Built-in analysis'?'good':'warn'}">${e(s.status)}</span></p><p>${e(s.description)}</p><dl class="brief-review"><dt>Works best when</dt><dd>${e(s.bestFor)}</dd><dt>Validate first</dt><dd>${e(s.watch)}</dd></dl><p><small>Evidence example: <a href="${e(s.source)}" target="_blank" rel="noopener">${e(s.sourceName)} ↗</a></small></p></div>`;}
export function setupView(c,r,ui={}){
 const step=ui.setupStep||1,issues=ui.setupErrors||[];
 let html=heading(1,'Start a campaign','Choose a useful goal and a screening route. Every suggested value remains editable.')+`<ol class="brief-progress" aria-label="Campaign setup progress">${['Goal','Screening system','Measurement','Review'].map((x,i)=>`<li ${step===i+1?'aria-current="step"':''}>${i+1}. ${x}</li>`).join('')}</ol>`;
 if(issues.length)html+=`<div class="callout error" role="alert"><strong>Complete the starting information</strong><ul>${issues.map(x=>`<li><a href="#f-${x.path.replaceAll('.','-')}" data-focus-field="${x.path}">${e(x.message)}</a></li>`).join('')}</ul></div>`;
 if(step===1)html+=`<fieldset><legend>Use a published campaign</legend><p>Start with its stated goal and screening route, then import the released data in Screen.</p><div class="template-cards">${Object.entries(publishedCampaignTemplates).map(([id,t])=>`<button type="button" data-action="published-template" data-template="${id}"><strong>${e(t.name)}</strong><span>${e(t.brief.objective)}</span></button>`).join('')}</div></fieldset><fieldset><legend>Or define a new goal</legend><div class="form-grid two">${field(c,'name','Campaign name',{placeholder:'e.g. LipA activity pilot'})}${field(r,'brief.parent','Parent enzyme',{placeholder:'Name or accession'})}${field(r,'brief.parentCloneId','Parent clone ID',{hint:'An exact tracking label, used in screen and stock records.'})}${field(r,'brief.objective','Useful improvement',{type:'textarea',wide:true,hint:'Describe the intended reaction and the improvement that would matter.'})}</div></fieldset>`;
 if(step===2)html+=`<fieldset><legend>How will you find promising variants?</legend>${field(r,'assay.screeningSystem','Screening system',{options:Object.entries(screeningSystems).map(([id,s])=>[id,s.name]),wide:true})}${screeningSystemSummary(r)}</fieldset>`+callout('The starting point fills in the route, sample format, signal unit and plate format where applicable. It does not supply a substrate, detector range or pass/fail threshold.','info');
 if(step===3)html+=`<fieldset><legend>What will you compare?</legend><div class="form-grid two">${field(r,'brief.metric','Improvement metric',{placeholder:'e.g. intended-product rate',suggestions:parameterSuggestions.metric})}${field(r,'brief.units','Metric units',{placeholder:'e.g. µM/min',suggestions:parameterSuggestions.units})}${field(r,'brief.conditions','Comparison conditions',{type:'textarea',wide:true,hint:'Record substrate, pH, temperature and normalization.'})}${field(r,'assay.sampleFormat','Sample format',{suggestions:parameterSuggestions.sampleFormat})}${field(r,'assay.normalization','Normalization basis',{suggestions:parameterSuggestions.normalization})}</div></fieldset>`+(r.assay.detection==='Other — planning only'?callout('This route can be planned and documented here, but needs an external analysis method.','warning'):callout('The built-in analyser fits linear rates from 96-well time courses. Confirm the actual assay range, controls and fitting window before analysis.'));
 if(step===4)html+=`<h3>Your starting brief</h3><dl class="brief-review">${[['Campaign',c.name],['Parent',r.brief.parent+' · '+r.brief.parentCloneId],['Intended benefit',r.brief.objective],['Screening system',screeningSystems[r.assay.screeningSystem]?.name],['Measurement',r.brief.metric+' · '+r.brief.units],['Conditions',r.brief.conditions],['Sample',r.assay.sampleFormat],['Normalization',r.assay.normalization]].map(([k,v])=>`<dt>${e(k)}</dt><dd>${e(v||'Not recorded')}</dd>`).join('')}</dl>`+callout('These are editable starting parameters, not a validated protocol. Establish the assay with the actual enzyme, matrix, instrument and controls.')+`<a class="button-like primary" href="#assay">Define and validate the assay →</a>`;
 html+=`<div class="actions">${step>1?'<button data-action="brief-back">← Back</button>':''}${step<4?'<button data-action="brief-next" class="primary">'+(step===1?'Choose a screening system →':step===2?'Use this starting point →':'Review the brief →')+'</button>':''}<a href="guide/index.html#campaign">Campaign guidance</a></div><p class="muted"><small>Suggested values are drawn from documented screening patterns and remain fully editable. Answers save as you type.</small></p>`;
 return html;
}
export function criteriaResults(r){
  const k=r.criteria;if(!k?.enabled)return[];
  if(!k.assayId.trim()||!Number.isFinite(k.fold)||k.fold<=0)return[{clone:'—',status:'Needs a named assay and a positive target ratio.'}];
  if(k.normalization!==r.review.normalization)return[{clone:'—',status:'Normalization differs from the confirmation view. Select compatible units before comparing.'}];
  let rows;try{rows=confirmationSummary(r.confirmation,r.review.parentCloneId,k.normalization);}catch(err){return[{clone:'—',status:err.message}];}
  rows=rows.filter(x=>x.assay_id===k.assayId&&x.clone_id!==r.review.parentCloneId);
  if(!rows.length)return[{clone:'—',status:'No observations for this exact assay ID. Free-text goals still require interpretation.'}];
  return rows.map(x=>({clone:x.clone_id,fold:x.fold,status:x.fold===null?'Comparable reference unavailable':(k.direction==='at_least'?x.fold>=k.fold:x.fold<=k.fold)?'Observed mean ratio meets the recorded target':'Observed mean ratio does not meet the recorded target'}));
}
export function goalContext(r){return`<section class="panel"><h3>Goal and confirmation context</h3><p><strong>Intended improvement:</strong> ${e(r.brief.objective||'Not recorded')}</p><p>${e(r.brief.metric||'Metric not recorded')} · ${e(r.brief.units||'Units not recorded')}<br>${e(r.brief.conditions||'Comparison conditions not recorded')}</p><p><strong>Properties to preserve:</strong> ${e(r.brief.secondary||'Not recorded')}</p><p>Screen reference: ${e(r.assay.reference_parent_id)} · Confirmation reference: ${e(r.review.parentCloneId)}<br>Comparison change: ${e(r.review.referenceReason||'None recorded')}</p><details><summary>Optional structured confirmation target</summary><p>Compare a dimensionless fold ratio only within a named assay and matching normalization. This describes observed means; it does not decide whether to advance a clone or establish statistical significance.</p><label class="check"><input type="checkbox" data-field="criteria.enabled" ${r.criteria.enabled?'checked':''}><span>Use a structured target alongside the written goal</span></label><div class="form-grid two">${field(r,'criteria.assayId','Exact confirmation assay ID')}${field(r,'criteria.normalization','Target normalization',{options:[['product','Product rate (µM/min)'],['enzyme','Product rate / enzyme concentration (min⁻¹)']]})}${field(r,'criteria.direction','Target direction',{options:[['at_least','At least this ratio'],['at_most','At most this ratio']]})}${field(r,'criteria.fold','Target fold versus reference',{type:'number',min:0})}${field(r,'criteria.notes','Target meaning / remaining uncertainties',{type:'textarea',wide:true})}</div></details><div id="criteria-output">${criteriaTable(r)}</div></section>`;}
export function criteriaTable(r){return r.criteria.enabled?table(['Clone','Observed fold','Target comparison'],criteriaResults(r).map(x=>[e(x.clone),num(x.fold,3),e(x.status)])):'<p>The written goal is retained for analyst interpretation.</p>';}
export function archiveContext(c,r){return`<section class="panel"><h3>Backup and external evidence</h3><p>Last backup download: ${e(date(c.lastExportAt))}<br>Last separate-copy restore: ${e(date(c.restorationCheckedAt))}</p><p>External backup: ${e(r.brief.backupLocation||'Location not recorded')}<br>Archive: ${e(r.review.archive||'Location not recorded')}</p><p>Sequence files and product/property evidence are external references unless explicitly imported. Keep those files beside the JSON backup. After restoring a separate copy, open its raw inputs and confirmation records and check these external locations.</p><button data-action="restore-check">Check a backup by restoring a separate copy</button></section>`;}
