import {field,heading,e,table,callout,num,date} from './ui.mjs';
import {confirmationSummary} from './core.mjs';
export const setupPaths=['name','brief.parent','brief.parentCloneId','brief.objective','brief.metric','brief.units','brief.conditions'];
export function setupIssues(c,r,step){const fields=step===1?[["name",c.name,"Give the campaign a name."],["brief.parent",r.brief.parent,"Name the parent enzyme."],["brief.parentCloneId",r.brief.parentCloneId,"Enter a parent clone ID for tracking."],["brief.objective",r.brief.objective,"Describe the improvement you want to measure."]]:[["brief.metric",r.brief.metric,"Name the improvement metric."],["brief.units",r.brief.units,"Enter the metric units."],["brief.conditions",r.brief.conditions,"Record the comparison conditions."]];return fields.filter(([,v])=>!String(v||'').trim()).map(([path,,message])=>({path,message}));}
export function setupView(c,r,ui={}){
 const step=ui.setupStep||1,issues=ui.setupErrors||[];
 let html=heading(1,'Define a useful improvement','A clear brief makes the assay, library and later decisions easier to connect.')+`<ol class="brief-progress" aria-label="Campaign brief progress">${['Useful improvement','Measurement route','Review brief'].map((x,i)=>`<li ${step===i+1?'aria-current="step"':''}>${i+1}. ${x}</li>`).join('')}</ol>`;
 if(issues.length)html+=`<div class="callout error" role="alert"><strong>Complete the starting information</strong><ul>${issues.map(x=>`<li><a href="#f-${x.path.replaceAll('.','-')}" data-focus-field="${x.path}">${e(x.message)}</a></li>`).join('')}</ul></div>`;
 if(step===1)html+=`<fieldset><legend>What should this enzyme do better?</legend><div class="form-grid two">${field(c,'name','Campaign name',{placeholder:'e.g. LipA activity pilot'})}${field(r,'brief.parent','Parent enzyme',{placeholder:'Name or accession'})}${field(r,'brief.parentCloneId','Parent clone ID',{hint:'An exact tracking label, used in screen and stock records.'})}${field(r,'brief.objective','Useful improvement',{type:'textarea',wide:true,hint:'Describe the intended reaction and the improvement that would matter.'})}</div></fieldset>`;
 if(step===2)html+=`<fieldset><legend>How will you make a fair comparison?</legend><div class="form-grid two">${field(r,'brief.metric','Improvement metric',{placeholder:'e.g. intended-product rate'})}${field(r,'brief.units','Metric units',{placeholder:'e.g. µM/min'})}${field(r,'brief.conditions','Comparison conditions',{type:'textarea',wide:true,hint:'Record substrate, pH, temperature and normalization.'})}${field(r,'assay.detection','Measurement route',{options:['Absorbance','Fluorescence','Luminescence','Other — planning only'],wide:true})}</div></fieldset>`+(r.assay.detection==='Other — planning only'?callout('You can plan and retain evidence here. This route needs an external analysis method; the built-in screen fits linear-rate plate measurements.','warning'):callout('The built-in screen fits linear rates from 96-well plate traces. Assay specificity, controls and independent confirmation still need to be established.'));
 if(step===3)html+=`<h3>Your starting brief</h3><dl class="brief-review">${[['Campaign',c.name],['Parent',r.brief.parent+' · '+r.brief.parentCloneId],['Intended benefit',r.brief.objective],['Measurement',r.brief.metric+' · '+r.brief.units],['Conditions',r.brief.conditions],['Readout route',r.assay.detection]].map(([k,v])=>`<dt>${e(k)}</dt><dd>${e(v||'Not recorded')}</dd>`).join('')}</dl>`+callout('This is a planning record. Filling it in does not establish assay validity or confirm an improved enzyme.')+`<a class="button-like primary" href="#assay">Define the assay →</a>`;
 html+=`<div class="actions">${step>1?'<button data-action="brief-back">← Back</button>':''}${step<3?'<button data-action="brief-next" class="primary">'+(step===1?'Choose the measurement route →':'Review the brief →')+'</button>':''}<a href="guide/index.html#campaign">Campaign guidance</a></div><p class="muted"><small>Answers save as you type. Return to any part of the brief or use the complete forms.</small></p>`;
 return html;
}
export function criteriaResults(r){
  const k=r.criteria;if(!k?.enabled)return[];
  if(!k.assayId.trim()||!Number.isFinite(k.fold)||k.fold<=0)return[{clone:'—',status:'Needs a named assay and a positive target ratio.'}];
  if(k.normalization!==r.review.normalization)return[{clone:'—',status:'Normalization differs from the confirmation view. Select compatible units before comparing.'}];
  let rows;try{rows=confirmationSummary(r.confirmation,r.review.parentCloneId,k.normalization);}catch(err){return[{clone:'—',status:err.message}];}
  rows=rows.filter(x=>x.assay_id===k.assayId&&x.clone_id!==r.review.parentCloneId);
  if(!rows.length)return[{clone:'—',status:'No observations for this exact assay ID. Free-text goals still require interpretation.'}];
  return rows.map(x=>({clone:x.clone_id,fold:x.fold,status:x.fold===null?'Comparable reference unavailable':(k.direction==='at_least'?x.fold>=k.fold:x.fold<=k.fold)?'Observed mean ratio meets the recorded target':'Observed mean ratio does not meet the recorded target'}));
}
export function goalContext(r){return`<section class="panel"><h3>Goal and confirmation context</h3><p><strong>Intended improvement:</strong> ${e(r.brief.objective||'Not recorded')}</p><p>${e(r.brief.metric||'Metric not recorded')} · ${e(r.brief.units||'Units not recorded')}<br>${e(r.brief.conditions||'Comparison conditions not recorded')}</p><p><strong>Properties to preserve:</strong> ${e(r.brief.secondary||'Not recorded')}</p><p>Screen reference: ${e(r.assay.reference_parent_id)} · Confirmation reference: ${e(r.review.parentCloneId)}<br>Comparison change: ${e(r.review.referenceReason||'None recorded')}</p><details><summary>Optional structured confirmation target</summary><p>Compare a dimensionless fold ratio only within a named assay and matching normalization. This describes observed means; it does not decide whether to advance a clone or establish statistical significance.</p><label class="check"><input type="checkbox" data-field="criteria.enabled" ${r.criteria.enabled?'checked':''}><span>Use a structured target alongside the written goal</span></label><div class="form-grid two">${field(r,'criteria.assayId','Exact confirmation assay ID')}${field(r,'criteria.normalization','Target normalization',{options:[['product','Product rate (µM/min)'],['enzyme','Product rate / enzyme concentration (min⁻¹)']]})}${field(r,'criteria.direction','Target direction',{options:[['at_least','At least this ratio'],['at_most','At most this ratio']]})}${field(r,'criteria.fold','Target fold versus reference',{type:'number',min:0})}${field(r,'criteria.notes','Target meaning / remaining uncertainties',{type:'textarea',wide:true})}</div></details><div id="criteria-output">${criteriaTable(r)}</div></section>`;}
export function criteriaTable(r){return r.criteria.enabled?table(['Clone','Observed fold','Target comparison'],criteriaResults(r).map(x=>[e(x.clone),num(x.fold,3),e(x.status)])):'<p>The written goal is retained for analyst interpretation.</p>';}
export function archiveContext(c,r){return`<section class="panel"><h3>Backup and external evidence</h3><p>Last backup download: ${e(date(c.lastExportAt))}<br>Last separate-copy restore: ${e(date(c.restorationCheckedAt))}</p><p>External backup: ${e(r.brief.backupLocation||'Location not recorded')}<br>Archive: ${e(r.review.archive||'Location not recorded')}</p><p>Sequence files and product/property evidence are external references unless explicitly imported. Keep those files beside the JSON backup. After restoring a separate copy, open its raw inputs and confirmation records and check these external locations.</p><button data-action="restore-check">Check a backup by restoring a separate copy</button></section>`;}
