import {e,table,callout,num} from './ui.mjs';
import {HEADERS,sourceRows,previewIssues} from './importer.mjs';
import {settingsPreview} from './workflow-ui.mjs';
import {assayConfig} from './data.mjs';
const inputID=key=>'import-'+key.replaceAll('.','-');
const input=(key,label,value='',options=null)=>`<label class="field" for="${inputID(key)}"><span>${e(label)}</span>${options?`<select id="${inputID(key)}" data-import="${e(key)}">${options.map(o=>{const[v,t]=Array.isArray(o)?o:[o,o];return`<option value="${e(v)}" ${String(value)===String(v)?'selected':''}>${e(t)}</option>`;}).join('')}</select>`:`<input id="${inputID(key)}" data-import="${e(key)}" value="${e(value)}">`}</label>`;
export function importView(c,r,p,error=''){
 const errorField=error?(p?.step===1&&!p.recipe.timeUnit?'import-timeUnit':p?.step===1?'import-layout':p?.step===2?'import-editor-wells':'screen-files'):null;
 const errorHTML=error?`<div class="callout error" id="import-error" tabindex="-1" role="alert"><strong>Import needs attention</strong><p>${e(error)}</p><a href="#${errorField}" data-import-focus="${errorField}">Return to the import controls →</a></div>`:'';
  let html=errorHTML+`<fieldset><legend>Import assistant · 96-well linear-rate screens</legend><p>Prepare the source files, inspect the conversion, then review the exact settings used for analysis.</p><label class="field"><span>Screen files</span><input type="file" id="screen-files" accept=".csv,.json,text/csv,application/json" multiple></label><p>CSV files may have any name. A map and clone register are optional if you assign identities below. Settings JSON is optional. Maximum combined input: 10 MB. <a href="guide/index.html#using-app">Import walkthrough →</a></p><p><a href="downloads/plate_map.csv" download>Plate map template</a> · <a href="downloads/clone_register.csv" download>Clone register template</a> · <a href="example/assay.json" download>Example settings</a></p></fieldset>`;
  if(!p)return html;
  html+=`<section class="import-panel"><ol class="import-progress" aria-label="Import progress">${['Map columns','Check identities','Review settings','Analyse'].map((label,i)=>`<li ${i+1===p.step?'aria-current="step"':''}>${i+1}. ${label}</li>`).join('')}</ol><h3>Step ${p.step} of 4 · ${['','Assign roles and columns','Check map and units','Review settings','Ready to analyse'][p.step]}</h3><p>Changes stay in this preview until analysis succeeds.</p>`;
  if(p.step===1){
    html+=`<div class="form-grid two">${input('layout','Measurement layout',p.recipe.layout,[['long','Long: one observation per row'],['wide','Wide: time column and well columns']])}${input('timeUnit','Time values in the source file',p.recipe.timeUnit,[['','Choose source units'],['seconds','Seconds'],['minutes','Minutes'],['milliseconds','Milliseconds']])}${input('decimal','Decimal mark',p.recipe.decimal,[['.','Decimal point'],[',','Decimal comma']])}${input('plateId','Plate ID if absent from observations',p.recipe.plateId)}${input('signalUnit','Raw signal unit (no activity conversion)',p.recipe.signalUnit)}</div>`;
    html+=conversionPreview(p);
    p.recipe.sources.forEach((s,i)=>{let keys=[],error='';if(s.role!=='settings')try{keys=Object.keys(sourceRows(p.originals.find(o=>o.name===s.name),s.delimiter)[0]||{}).filter(k=>k!=='_line');}catch(err){error=err.message;}
      html+=`<fieldset><legend>${e(s.name)}</legend><div class="form-grid two">${input(`sources.${i}.role`,'File role',s.role,[['unused','Ignore for analysis'],['measurements','Measurements'],['map','Plate map'],['register','Clone register'],['settings','Assay settings JSON']])}${s.role!=='settings'?input(`sources.${i}.delimiter`,'CSV separator',s.delimiter,[[',','Comma'],[';','Semicolon'],['\t','Tab']]):''}</div>${error?callout(e(error),'warning'):''}`;
      if(s.role==='measurements'&&p.recipe.layout==='wide')html+=input('wideTime','Time column',p.recipe.wideTime||'', [['','Choose a column'],...keys]);
      else if(HEADERS[s.role])html+=`<details open><summary>Confirm selected columns</summary><p>Unmapped metadata uses the visible assay settings or supplied plate ID. Measurement values and sample identities require explicit columns or map assignments.</p><div class="form-grid two">${HEADERS[s.role].map(h=>input(`sources.${i}.columns.${h}`,h,s.columns[h]||'',[['','Not mapped'],...keys])).join('')}</div></details>`;
      html+='</fieldset>';
    });
    html+=`<details><summary>Saved mapping presets</summary><label class="field"><span>Preset</span><select id="mapping-preset">${c.mappingPresets.map((v,i)=>`<option value="${i}">${e(v.name)}</option>`).join('')}</select></label><button data-action="apply-preset" ${c.mappingPresets.length?'':'disabled'}>Preview preset</button><p>File roles are matched before loading column and unit choices. Review every new import.</p></details><button data-action="map-preview" class="primary">Confirm columns and preview map</button>`;
  }
  if(p.step===2){
    const m=p.mapped,issues=previewIssues(m,p.config),plates=[...new Set(m.measurements.map(x=>x.plate_id))],plate=p.editor.plate||plates[0];
    html+=`<p>${num(m.measurements.length,0)} observations · ${m.map.length} mapped wells · times converted from ${e(p.recipe.timeUnit)} to seconds · signal ${e(p.recipe.signalUnit)}. Source labels and run identity are retained in the table below.</p>${issues.length?callout('<strong>Resolve '+issues.length+' map or timing issues.</strong><ul>'+issues.slice(0,12).map(x=>'<li>'+e(x)+'</li>').join('')+'</ul>'+(issues.length>12?'<p>Further issues will be listed as these are corrected.</p>':''),'warning'):callout('Map identities, fitting times and stock references pass the preview checks. The full analyser checks control quality next.')}`;
    html+=`<fieldset><legend>Edit plate identities</legend><p>Select one well to inspect its identity, or enter several coordinates separated by commas. Bulk assignment uses one explicit clone and preparation; selected wells become technical replicates 1, 2, … in the entered order.</p><div class="form-grid two">${input('editor.plate','Plate to edit',plate,plates)}${input('editor.wells','Wells to assign (e.g. A01, A02)',p.editor.wells)}${input('editor.sample_type','Sample type',p.editor.sample_type,['candidate','parent','blank','host'])}${input('editor.clone_id','Clone ID',p.editor.clone_id)}${input('editor.prep_id','Independent preparation ID',p.editor.prep_id)}${input('editor.stock_location','Stock location',p.editor.stock_location)}</div><button data-action="assign-wells">Apply identity to selected wells</button><button data-action="remove-map-wells">Remove selected map entries</button><div class="table-wrap"><table class="plate"><caption>Editable 96-well map · ${e(plate)}</caption><tbody>${'ABCDEFGH'.split('').map(letter=>'<tr><th>'+letter+'</th>'+Array.from({length:12},(_,j)=>{const well=letter+String(j+1).padStart(2,'0'),row=m.map.find(x=>x.plate_id===plate&&x.well===well);return`<td><button data-action="edit-map-well" data-well="${well}" class="${e(row?.sample_type||'')}" aria-label="Edit ${well} ${e(row?.clone_id||row?.sample_type||'unassigned')}">${well}<br>${e(row?.clone_id||row?.sample_type||'—')}</button></td>`;}).join('')+'</tr>').join('')}</tbody></table></div></fieldset>`;
    html+=`<details><summary>All map identities and stock references</summary>${table(['Plate / well','Type','Clone','Preparation / technical well','Stock'],m.map.map(x=>[e(x.plate_id+'/'+x.well),e(x.sample_type),e(x.clone_id),e(x.prep_id+'/'+x.technical_rep),e(m.register.find(c=>c.clone_id===x.clone_id)?.stock_location)]))}</details><details><summary>First 12 canonical observations</summary>${table(HEADERS.measurements,m.measurements.slice(0,12).map(x=>HEADERS.measurements.map(k=>e(x[k]))))}</details><div class="actions"><button data-action="import-back">Back to columns</button><button data-action="validate-import" class="primary">Check controls and review settings</button></div>`;
  }
  if(p.step>=3){html+=settingsPreview(assayConfig(r.assay),p.config);if(p.quality)html+=table(['Plate','Control check'],Object.entries(p.quality).map(([plate,q])=>[e(plate),q.usable?'Pass configured rules':'Review: '+e(q.reasons.join('; '))]));html+=`<p>${p.reviewRecord?'These exact settings are acknowledged.':'Review references, units, fitting times, limits and thresholds before acknowledging.'}</p><div class="actions"><button data-action="import-map-back">Back to map</button><button data-action="review-import">I have reviewed these imported settings</button><button data-action="analyze" class="primary" ${p.reviewRecord?'':'disabled'}>Analyse and retain this import</button></div><details><summary>Reuse this mapping</summary><label class="field"><span>Mapping preset name</span><input id="preset-name" placeholder="e.g. Reader CSV export"></label><button data-action="save-preset">Save mapping preset</button><p>Presets retain column/unit choices only; identities are reviewed afresh.</p></details>`;}
  return html+'<div class="actions"><button data-action="cancel-import">Cancel import</button></div></section>';
}

export function conversionPreview(p){
 if(!p?.recipe.timeUnit)return '<p class="field-error" id="import-timeUnit-hint">Choose the time unit from the source export before previewing the map.</p>';
 const source=p.recipe.sources.find(s=>s.role==='measurements');if(!source)return '';
 try{const rows=sourceRows(p.originals.find(o=>o.name===source.name),source.delimiter),column=p.recipe.layout==='wide'?p.recipe.wideTime:source.columns.time_s,factor={seconds:1,minutes:60,milliseconds:.001}[p.recipe.timeUnit];if(!column)return '<p class="selection-note">Map a time column to inspect conversion into seconds.</p>';const samples=[...new Set(rows.map(r=>r[column]))].slice(0,4);return `<div class="conversion-preview"><strong>Time conversion preview</strong>${table(['Source value ('+p.recipe.timeUnit+')','Analysis time (s)'],samples.map(v=>{const clean=String(v??'').trim(),n=clean===''?NaN:Number(p.recipe.decimal===','?clean.replace(',','.'):clean);return[e(v),Number.isFinite(n)?num(n*factor,6):'Invalid time value'];}))}<small>Original exports remain unchanged. Analysis retains the conversion recipe and canonical inputs.</small></div>`;}catch{return '';}
}
