import{e,heading,table,metric,callout,help,num,pct,tag,date}from'./ui.mjs';
import{assayConfig}from'./data.mjs';
import{linePlot}from'./charts.mjs';
export const decisions={retest_candidate:'Nominate for retest',review_measurement:'Review measurement',below_retest_threshold:'Below retest threshold'};
export function selectedAnalysis(r,ui){return r.analyses.find(a=>a.id===ui.analysisId)||r.analyses.at(-1);}
export function screenView(c,r,ui){
  const run=selectedAnalysis(r,ui);let html=heading(6,'Screen and inspect','Join the plate map, clone register, and raw observations; inspect quality before nominating candidates.');
  html+=`<fieldset><legend>Import a 96-well linear-rate screen</legend><p>Select <span class="code">plate_map.csv</span>, <span class="code">clone_register.csv</span>, and <span class="code">measurements.csv</span>. You may include <span class="code">assay.json</span> to stage its settings with the import. Maximum combined CSV size: 10 MB.</p><label class="field"><span>Screen files</span><input type="file" id="screen-files" accept=".csv,.json,text/csv,application/json" multiple></label><p><a href="downloads/plate_map.csv" download>Blank plate map</a> · <a href="downloads/clone_register.csv" download>Clone register</a> · <a href="downloads/measurements.csv" download>Measurements</a> · <a href="example/assay.json" download>Example settings</a></p><small>Files are analyzed in this browser. The first release uses the toolkit CSV format; other instrument exports need column conversion.</small></fieldset>`;
  if(ui.importError)html+=callout(e(ui.importError),'error');
  if(ui.pending){html+=`<div class="callout info"><strong>Import preview</strong><p>Rows parsed successfully. Identity, units, controls, and complete fitting times are checked when you analyze.</p>${table(['File','Rows','Size'],Object.entries(ui.pending.files).map(([name,f])=>[e(name),num(f.rows,0),num(f.bytes/1024,1)+' KB']))}${ui.pending.config?'<p>Analysis will use the imported assay settings. They will become the current assay settings after a successful run.</p>':''}<div class="actions"><button class="primary" type="button" data-action="analyze" ${ui.analyzing?'disabled':''}>${ui.analyzing?'Analyzing…':'Analyze imported screen'}</button><button type="button" data-action="cancel-import" ${ui.analyzing?'disabled':''}>Cancel import</button></div></div>`;}
  else if(Object.keys(r.files).length)html+=`<div class="actions"><button class="primary" type="button" data-action="reanalyze" ${ui.analyzing?'disabled':''}>${ui.analyzing?'Analyzing…':'Analyze retained files with current settings'}</button></div>`;
  if(!run)return html+`<div class="empty"><h3>No analyzed screen yet</h3><p>Open the worked example to inspect a complete synthetic screen, or import your mapped raw data above.</p><button type="button" data-action="demo">Open worked example</button></div>`+help('Supported analysis','96-well plates, at least three configured timepoints, one preparation per candidate per plate. Multiple plates are evaluated independently. Endpoint assays, nonlinear kinetics and pooled cross-plate rankings need separate methods.','toolkit');
  const result=run.result,plates=Object.keys(result.quality),plate=plates.includes(ui.plate)?ui.plate:plates[0],q=result.quality[plate],wells=result.wells.filter(w=>w.plate_id===plate),well=wells.find(w=>w.well===ui.well)||wells.find(w=>w.clone_id===result.candidates.find(x=>x.plate_id===plate)?.clone_id)||wells[0];
  html+=`<fieldset><legend>Saved analysis</legend><div class="form-grid two"><label class="field"><span>Run snapshot</span><select id="analysis-select">${r.analyses.map(a=>`<option value="${e(a.id)}" ${a.id===run.id?'selected':''}>${e(a.label)} · ${e(date(a.createdAt))}</option>`).join('')}</select></label><label class="field"><span>Plate</span><select id="plate-select">${plates.map(p=>`<option ${p===plate?'selected':''}>${e(p)}</option>`).join('')}</select></label></div><small>Engine ${e(result.engineVersion)} · ${e(result.config.assay_id)} · ${e(result.config.run_id)} · ${num(result.counts.observations,0)} raw observations</small></fieldset>`;
  if(JSON.stringify(assayConfig(r.assay))!==JSON.stringify(result.config))html+=callout('You are viewing a saved analysis. Current assay settings differ; retained results keep their original settings until you run a new analysis.','warning');
  html+=callout(`<strong>Data origin:</strong> ${e(result.config.data_origin)}<br><small>Imported row labels: ${result.dataOrigins.map(e).join('; ')}</small>`,/synthetic|demo|teaching/i.test(result.config.data_origin)?'info':'');
  html+=q.usable?callout('<strong>Plate passes the configured control rules.</strong> Nominations still require independent confirmation.'):callout('<strong>Plate requires review; candidate nomination is blocked.</strong><br>'+q.reasons.map(x=>e(x.replaceAll('_',' '))).join('; '),'error');
  html+=`<div class="metrics">${metric(num(q.parent_rate_per_min,5),'Parent rate ('+result.config.signal_unit+'/min)')}${metric(pct(q.parent_cv),'Parent-preparation CV')}${metric(q.parent_prep_count,'Valid parent preparations')}</div><h3>Plate map · ${e(plate)}</h3><p>Choose a well to inspect its raw trace and sample identity.</p><div class="table-wrap"><table class="plate"><caption>96-well map; flags and identities are included in each well label.</caption><thead><tr><th scope="col">Well</th>${Array.from({length:12},(_,i)=>`<th scope="col">${i+1}</th>`).join('')}</tr></thead><tbody>${'ABCDEFGH'.split('').map(letter=>`<tr><th scope="row">${letter}</th>${Array.from({length:12},(_,i)=>{const coord=letter+String(i+1).padStart(2,'0'),w=wells.find(x=>x.well===coord);if(!w)return'<td>—</td>';const cand=result.candidates.find(x=>x.plate_id===plate&&x.clone_id===w.clone_id),flags=uniqueFlags(w,cand);return`<td><button type="button" data-action="well" data-well="${coord}" data-plate="${e(plate)}" class="${w.sample_type} ${flags?'flagged':''} ${well.well===coord?'selected':''}" aria-label="${e(coord+' '+(w.clone_id||w.sample_type)+' '+w.sample_type+(flags?', '+flags:''))}" aria-pressed="${well.well===coord}" title="${e(w.clone_id||w.sample_type)}">${e(w.clone_id||{blank:'BLK',host:'HOST'}[w.sample_type]||coord)}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div><div class="legend"><span style="--key:#d1e7d6">Parent</span><span style="--key:#dae9f1">Host</span><span style="--key:#eee">Blank</span><span style="--key:#eef4ef">Candidate</span><span style="--key:#d7a14b">Review flag</span></div>`;
  const siblings=well.clone_id?wells.filter(w=>w.clone_id===well.clone_id&&w.prep_id===well.prep_id):[well];
  const series=siblings.slice(0,4).map(w=>({name:w.well+' '+(w.clone_id||w.sample_type),points:w.points}));
  html+=`<section class="panel"><h3>Selected: ${e(well.well)} · ${e(well.clone_id||well.sample_type)}</h3><p>Preparation: ${e(well.prep_id||'Control')} · Stock: ${e(well.stock_location||'Not applicable')}</p>${well.flags.length?callout(well.flags.map(f=>e(f.replaceAll('_',' '))).join('; '),'warning'):''}${linePlot(series,{yLabel:result.config.signal_unit,title:'Raw reaction traces for '+(well.clone_id||well.well)})}${table(['Well','Raw slope/min','R²','Corrected rate/min'],siblings.map(w=>[e(w.well),num(w.raw_slope_per_min,6),num(w.r2,5),num(w.corrected_rate_per_min,6)]))}<details><summary>Raw observations and fitting times</summary><p>Fit uses these exact seconds: ${result.config.fit_times_s.map(e).join(', ')}. Other timepoints remain in the raw files.</p>${table(['Well','Time (s)','Signal','In fit'],siblings.flatMap(w=>w.points.map(([t,y])=>[e(w.well),num(t),num(y,8),result.config.fit_times_s.includes(t)?'Yes':'No'])))}</details></section>`;
  let filtered=result.candidates.filter(x=>x.plate_id===plate);if(ui.filter&&ui.filter!=='all')filtered=filtered.filter(x=>x.decision===ui.filter);if(ui.search)filtered=filtered.filter(x=>(x.clone_id+' '+x.stock_location).toLowerCase().includes(ui.search.toLowerCase()));
  html+=`<h3 style="margin-top:20px">Candidate review</h3><div class="form-grid two"><label class="field"><span>Decision filter</span><select id="candidate-filter">${[['all','All candidates'],...Object.entries(decisions)].map(([v,t])=>`<option value="${v}" ${ui.filter===v?'selected':''}>${e(t)}</option>`).join('')}</select></label><label class="field"><span>Find clone or stock</span><input id="candidate-search" value="${e(ui.search||'')}" type="search"></label></div>${table(['Clone','Fold vs parent','Technical CV','Decision / flags','Stock'],filtered.map(x=>[`<button type="button" data-action="clone" data-clone="${e(x.clone_id)}" data-plate="${e(plate)}">${e(x.clone_id)}</button>`,x.fold_vs_parent===null?'Unavailable':num(x.fold_vs_parent,3)+'×',pct(x.technical_cv),tag(decisions[x.decision],x.decision==='retest_candidate'?'good':x.flags?'warn':'')+(x.flags?'<br><small>'+e(x.flags.replaceAll('_',' ').replaceAll(';','; '))+'</small>':''),e(x.stock_location)]))}<details><summary>Controls, settings and file provenance</summary>${table(['Control metric','Value'],[['Blank slope/min',num(q.blank_slope_per_min,6)],['Host rate/min',num(q.host_rate_per_min,6)],['Descriptive Z′',num(q.zprime_descriptive,3)],['Plate reasons',q.reasons.map(e).join('; ')||'None under configured rules']])}<p>Z′ is descriptive; it is not used to nominate candidates. Parent CV uses independent preparation means.</p>${table(['Input file','SHA-256'],Object.values(run.inputFiles).map(f=>[e(f.name),`<span class="code">${e(f.sha256)}</span>`]))}<pre class="code">${e(JSON.stringify(result.config,null,2))}</pre></details><div class="actions"><button data-action="candidates-csv" type="button">Export candidates</button><button data-action="wells-csv" type="button">Export well results</button><button data-action="quality-json" type="button">Export quality &amp; settings</button><button data-action="raw-export" type="button">Export this run's raw inputs</button></div>`;
  return html;
}
function uniqueFlags(w,c){return [...new Set([...w.flags,...(c?.flags?c.flags.split(';'):[])])].join('; ');}
